spec:
  replicas: 1
  template:
    spec:
      containers:
        - env:
          - name: JAVA_OPTS
            value: >-
                -Djavax.net.ssl.trustStore=/quarkus-camel-native-example/config/badssl.cacerts
                -Djavax.net.ssl.trustStorePassword=changeit
          args:
            - '-Djavax.net.ssl.trustStore=/quarkus-camel-native-example/config/badssl.cacerts'
            - '-Djavax.net.ssl.trustStorePassword=changeit'
          resources:
            requests:
              cpu: 100m
              memory: 200Mi
            limits:
              cpu: 800m
              memory: 800Mi
          volumeMounts:
            - mountPath: /quarkus-camel-native-example/config/application.properties
              name: quarkus-camel-native-example-configvolume
              readOnly: true
              subPath: application.properties
            - mountPath: /quarkus-camel-native-example/config/badssl.cacerts
              name: badssl-cacerts-secretvolume
              readOnly: true
              subPath: badssl.cacerts
      volumes:
        - name: quarkus-camel-native-example-configvolume
          configMap:
            name: quarkus-camel-native-example
            optional: false
        - name: badssl-cacerts-secretvolume
          secret:
            secretName: quarkus-camel-native-example
            optional: false
