apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: quarkus-camel-native-example
  name: quarkus-camel-native-example
spec:
  endpoints:
  - interval: 15s
    targetPort: 8080
    path: /q/metrics
    scheme: http
  selector:
    matchLabels:
      app: quarkus-camel-native-example